language: cpp

before_install:
  - apt-get install -y doxygen doxygen-latex graphviz
script:
  - doxygen
deploy:
  provider: pages
  local-dir: html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
